pybo/views/diary_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g
from werkzeug.utils import redirect

from .. import db
from ..models import Diary
from ..forms import DiaryForm, MusicRecForm
from pybo.views.auth_views import login_required

import pandas as pd
import numpy as np
from numpy import dot
from numpy.linalg import norm
import warnings
warnings.filterwarnings('ignore')




bp = Blueprint('diary', __name__, url_prefix='/diary')


@bp.route('/list/')
def _list():
    diary_list = Diary.query.order_by(Diary.create_date.desc())
    return render_template('diary/diary_list.html', diary_list=diary_list)


@bp.route('/detail/<int:diary_id>/')
def detail(diary_id):
    form = MusicRecForm()
    diary = Diary.query.get(diary_id)
    return render_template('diary/diary_detail.html', diary=diary, form=form)


@bp.route('/create/', methods=['GET', 'POST'])
@login_required
def create():
    form = DiaryForm()
    if request.method == 'POST' and form.validate_on_submit():
        diary = Diary(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(diary)
        db.session.commit()
        return render_template('diary/diary_detail.html', diary=diary, form=form) # 작성을 하면 목록 화면(main.index)으로 가는 상태니까 바로 디테일 화면(diary.detail)으로 가게끔
    return render_template('diary/diary_form.html', form=form)

pybo/views/musicrec_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g
from werkzeug.utils import redirect

from .. import db
from ..forms import MusicRecForm
from ..models import Diary, MusicRec
from .auth_views import login_required
from .recsys_step3 import recsys_step3
import pandas as pd
import numpy as np
from numpy import dot
from numpy.linalg import norm
bp = Blueprint('musicrec', __name__, url_prefix='/musicrec')


def cos_sim(A, B):
    return dot(A, B) / (norm(A) * norm(B))


def reco(emotion_list, data):
    if emotion_list[0] == max(emotion_list):  # 기쁨
        em1_idx = data[data['emotion max'].str.contains('행복한')].index.to_list()  # 기쁨일 경우 행복한과 경쾌한을 max_tag로 가진 노래를 선택
        em2_idx = data[data['emotion max'].str.contains('경쾌한')].index.to_list()
        em3_idx = list(set(em1_idx + em2_idx))

        rec_data = data.iloc[em3_idx].iloc[:5]  # 5개를 먼저 추천 (fin_score 기준)
        idx = list(data.index)
        score = []
        for i in rec_data['곡 제목']:
            score.append(input(f'{i}의 점수를 입력해주세요! (5점 만점) ', ))  # 사용자에게 곡에 대한 점수를 5점 척도로 받는다.
        rec_data['score'] = score
        mx = rec_data[rec_data['score'] == max(score)].index.to_list()
        max_ems = [[data['우울한'][i], data['울고싶은'][i], data['긴장되는'][i], data['무서운'][i], data['잔잔한'][i], data['행복한'][i],
                    data['경쾌한'][i], data['편안한'][i]] for i in mx]
        ems = [[data['우울한'][i], data['울고싶은'][i], data['긴장되는'][i], data['무서운'][i], data['잔잔한'][i], data['행복한'][i],
                data['경쾌한'][i], data['편안한'][i]] for i in idx]

        data['cos'] = 0
        for n in range(len(mx)):
            cos = pd.Series([cos_sim(ems[i], max_ems[n]) for i in
                             range(len(data))])  # 사용자가 가장 높은 점수를 준 곡의 8가지 감정을 기준으로 코사인 유사도를 구한다.
            cos.index = idx
            data['cos'] += cos
            print(f'{n}번째 코사인 유사도 계산완료')

        data = data[5:]  # 현재 추천한 5곡을 제외하여 데이터 다시 설정
        data = data.sort_values(by='cos', ascending=False)  # 계산한 코사인 유사도를 기준으로 정렬처리
        # print(data.head())
        return data

    elif emotion_list[1] == max(emotion_list):  # 분노
        em1_idx = data[data['emotion max'].str.contains('긴장되는')].index.to_list()  # 감정에 충실한 데이터셋
        em2_idx = data[data['emotion max'].str.contains('경쾌한')].index.to_list()  # 감정과 반대되는 데이터셋

        rec_data_s = data.iloc[em1_idx]
        rec_data_d = data.iloc[em2_idx]

        s = rec_data_s.iloc[0]
        d = rec_data_d.iloc[0]
        c = pd.concat([s, d])
        # ex = [i for i in c.index.to_list()]

        name = list(c['곡 제목'])

        score = []
        for n, i in enumerate(name):
            print(f'{n + 1}번:{i}')
        result = int(input('더 맘에 드는 노래 번호를 입력해주세요'))
        dataset = ''

        # data.drop(index=ex)
        if result == 1:  # 사용자가 감정에 충실한 노래를 선택
            dataset = data.iloc[em1_idx]
            print('긴장되는 노래 선택 dataset = 긴장되는')
        elif result == 2:  # 사용자가 감정에 반대되는 노래를 선택
            dataset = data.iloc[em2_idx]
            print('경쾌한 노래 선택 dataset = 경쾌한')
        else:
            print('1 또는 2를 입력하세요!')

        return dataset



    else:  # 분노
        em1_idx = data[data['emotion max'].str.contains('우울한')].index.to_list()  # 감정에 충실한 데이터셋
        em2_idx = data[data['emotion max'].str.contains('울고싶은')].index.to_list()
        em12_idx = list(set(em1_idx + em2_idx))

        em3_idx = data[data['emotion max'].str.contains('편안한')].index.to_list()  # 감정과 반전되는 데이터셋
        em4_idx = data[data['emotion max'].str.contains('잔잔한')].index.to_list()
        em34_idx = list(set(em3_idx + em4_idx))

        rec_data_s = data.iloc[em12_idx]
        rec_data_d = data.iloc[em34_idx]

        s = rec_data_s.iloc[0]
        d = rec_data_d.iloc[0]
        c = pd.concat([s, d])
        # ex = [i for i in c.index.to_list()]

        name = list(c['곡 제목'])

        score = []
        for n, i in enumerate(name):
            print(f'{n + 1}번:{i}')
        result = int(input('더 맘에 드는 노래 번호를 입력해주세요'))
        dataset = ''

        # data.drop(index=ex)
        if result == 1:  # 사용자가 감정에 충실한 노래를 선택
            dataset = data.iloc[em1_idx]
            print('우울한, 울고싶은 노래 선택 dataset = 우울한, 울고싶은')
        elif result == 2:  # 사용자가 감정에 반대되는 노래를 선택
            dataset = data.iloc[em2_idx]
            print('편안한, 잔잔한 노래 선택 dataset = 편안한, 잔잔한')
        else:
            print('1 또는 2를 입력하세요!')

        return dataset


def reco2(data):  # 두번째 추천
    rec_data = data.iloc[:5]

    idx = list(data.index)
    score = []
    for i in rec_data['곡 제목']:
        score.append(input(f'{i}의 점수를 입력해주세요! (5점 만점) ', ))  # 사용자에게 곡에 대한 점수를 5점 척도로 받는다.
    rec_data['score'] = score
    mx = rec_data[rec_data['score'] == max(score)].index.to_list()
    max_ems = [[data['우울한'][i], data['울고싶은'][i], data['긴장되는'][i], data['무서운'][i], data['잔잔한'][i], data['행복한'][i],
                data['경쾌한'][i], data['편안한'][i]] for i in mx]
    ems = [[data['우울한'][i], data['울고싶은'][i], data['긴장되는'][i], data['무서운'][i], data['잔잔한'][i], data['행복한'][i],
            data['경쾌한'][i], data['편안한'][i]] for i in idx]

    data['cos'] = 0
    for n in range(len(mx)):  # 가장 높은 점수를 준 노래의 8가지 감정값을 기준으로 코사인 유사도를 계산한다.
        cos = pd.Series([cos_sim(ems[i], max_ems[n]) for i in range(len(data))])
        cos.index = idx
        data['cos'] += cos
        print(f'{n}번째 코사인 유사도 계산완료')

    data = data[5:]
    data = data.sort_values(by='cos', ascending=False)
    # print(data.head())

    a = int(input('추천 계속 = 1, 추천 멈추기 = 0', ))  # 0입력시 추천 종료
    # mx = rec_data.index(max(score))
    data = data[5:]
    if a == 0:
        return
    else:
        reco2(data)


def recsys_step4(emotion_list, text, weights):
    data = recsys_step3(emotion_list, text, weights)
    #data = pd.read_csv('recys_step3_result.csv')
    data = data.drop_duplicates(['song id'], keep='first')
    data = data.reset_index()
    data = data.drop(['index'], axis=1)
    rec_data = reco(emotion_list, data)
    rec2_data = reco2(rec_data)
    return rec2_data

@bp.route('/recommend/<int:diary_id>', methods=['GET','POST'])
@login_required
def recommend(diary_id):
    form = MusicRecForm()
    diary = Diary.query.get_or_404(diary_id)
    musicname = request.form.get('musicname',False)
    if request.method == 'POST' and form.validate_on_submit():
        lyr1 = float(request.form['lyrpre'])
        emo1 = float(request.form['emopre'])
        weights = [lyr1, emo1]
        emotion_list = [0.1, 0.88, 0.02]
        rec_result = recsys_step4(emotion_list, diary, weights)
        rec_result.to_csv('web_result.csv', encodings='utf-8-sig')
    # POST 폼 방식으로 전송된 데이터 항목 중 name 속성이 musicname인 값
    musicrec = MusicRec(musicname=musicname, create_date=datetime.now(), user=g.user)
    diary.musicrec_set.append(musicrec)
    db.session.commit()
    return render_template('diary/diary_detail.html', diary=diary, form=form, emopre=emo1, lyrpre=lyr1)

pybo/templates/diary/diary_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-5">
            <h4 class="subtitle wow fadeInUp animated"data-wow-delay=".3s" data-wow-duration="500ms">{{ diary.subject }}</h4>
            <div class="card-body">
                <div class="d-flex justify-content-start">
                    <div class="badge badge-light p-2">
                        {{ diary.create_date|datetime }}
                    </div>
                </div>
                <div class="card-text">{{ diary.content|markdown }}</div>
            </div>
        </div>
        {% for musicrec in diary.musicrec_set %}
        <div class="col-md-7">
            <h4 class="subtitle wow fadeInUp animated" data-wow-delay=".3s" data-wow-duration="500ms">노래 정보</h4>
            <div class="card">
                <div class="row no-gutters">
                    <div class="col-4">
                        <img src="{{ url_for('static', filename = 'images/card-image.png')}}" alt="album cover image" class="img-responsive" width="150" height="150">
                        <div class="overlay">
                            <div class="buttons">
                                <a rel="gallery" class="fancybox" href="images/card-image.png">Demo</a>
                                <a target="_blank" href="#">Details</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-8">
                        <div class="card-body">
                            <div class="card-text">노래 제목: {{ musicrec.musicname}}</div>
                            <div class="card-text">가수: {{ musicrec.singer}}</div>
                            <div class="card-text">장르: {{ musicrec.genre}}</div>
                            <p>1<input type="range" name="grade" min="1" max="5">5</p> <!-- 이거 어디서 POST 해서 받아야되는데-->
                        </div>
                    </div>
                </div>
            </div>
            <h4 class="subtitle wow fadeInUp animated" data-wow-delay=".3s" data-wow-duration="500ms">노래 가사</h4>
            <div class="card-body">
                <div class="card-text">가사 나오는 곳 {{ musicrec.lyrics}}</div>
            </div>
        </div>
    </div>
    {% endfor %}

    <form action="{{ url_for('musicrec.recommend', diary_id=diary.id) }}" method="post" class="my-3">
        <input type="submit" value="노래추천결과" onclick="this.style.visibility='hidden'" class="btn btn-primary">
    </form>

</div>
<br><br>
<a href="{{ url_for('diary._list') }}">메인화면으로 돌아가기</a>
{% endblock %}

pybo/templates/diary/diary_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">오늘의 일기를 써보아요</h5>
    <form method="post" class="post-form my-3">

        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <!-- 오류표시 End -->

        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.data or '' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>

        <div class="form-group">
            <label for="lyrpre">가사 중요도</label>
            <input type="number" class="form-control" name="lyrpre" id = "lyrpre">
        </div>
        <div class="form-group">
            <label for="emopre">감정 중요도</label>
            <input type="number" class="form-control" name="emopre" id = "emopre">
        </div>

        <button type="submit" class="btn btn-primary">일기 작성 완료!</button>
        <h6>오늘의 기분에 어울리는 노래를 추천해줄게요</h6>
    </form>
</div>
{% endblock %}

pybo/templates/diary/diary_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="block">
                <h2>Big Headline for Portfolio Project</h2>
                <div class="portfolio-meta">
                   <span>Dec 11, 2020</span>|
                   <span> Category: typography</span>|
                   <span> website: <a href="http://www.themefisher.com">Themefisher</a></span>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-md-10"> <!--위치 변경 -->
<a href="{{ url_for('diary.create') }}" class="btn btn-secondary">일기쓰기</a>
</div>

<div class="container my-3">
    <table class="table">
        <tbody>
        {% if diary_list %}
        {% for diary in diary_list %}
        <tr>
            <td>
                <a href="{{ url_for('diary.detail', diary_id=diary.id) }}">{{ diary.subject }}</a>
                <p>{{ diary.content }}</p>
            </td>
            <td>{{ diary.create_date|datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">일기가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}